# Generated by Django 5.1.6 on 2025-02-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0002_remove_medication_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(editable=False, max_length=255)),
                ('dose', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication')),
            ],
        ),
    ]
