# Generated by Django 5.1.6 on 2025-05-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(editable=False, max_length=255)),
                ('dose', models.CharField(max_length=50)),
                ('quantity_administered', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_doses', to='residents.resident')),
            ],
        ),
    ]
