# Generated by Django 5.1.6 on 2025-05-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_dose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdose',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('taken', 'Tomada'), ('skipped', 'Omitida'), ('deleted', 'Eliminada')], default='scheduled', max_length=10),
        ),
    ]
