# Generated by Django 5.1.6 on 2025-02-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_dose', '0001_initial'),
        ('residents', '0002_rename_medication_resident_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdose',
            name='resident',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medication_doses', to='residents.resident'),
        ),
    ]
