# Generated by Django 5.1.6 on 2025-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_dose', '0005_alter_medicationdose_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationdose',
            name='quantity_administered',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
