# Generated by Django 5.1.6 on 2025-05-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('medical_condition', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
            options={
                'unique_together': {('resident', 'medication')},
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='medications',
            field=models.ManyToManyField(related_name='residents_with_quantity', through='residents.ResidentMedication', to='medications.medication'),
        ),
    ]
