# Generated by Django 5.1.6 on 2025-02-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='medication',
            new_name='medications',
        ),
    ]
