# Generated by Django 5.1.6 on 2025-05-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supply')),
            ],
            options={
                'unique_together': {('resident', 'supply')},
            },
        ),
    ]
