# Generated by Django 5.1.6 on 2025-05-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_residentsupply'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='supplies',
            field=models.ManyToManyField(related_name='residents_with_quantity', through='residents.ResidentSupply', to='supplies.supply'),
        ),
    ]
