# Generated by Django 5.1.6 on 2025-05-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medication_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('medication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='medications.medication')),
            ],
        ),
    ]
