# Generated by Django 5.1.6 on 2025-04-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_patients'),
        ('residents', '0002_rename_medication_resident_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrator_profile', to='residents.resident'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('administrator', 'Administrador'), ('family', 'Familiar')], max_length=13),
        ),
    ]
